# Generated by Django 4.2.7 on 2024-11-20 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirección', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('ci', models.IntegerField(max_length=11)),
                ('salario_mensual', models.FloatField()),
                ('cuota', models.FloatField()),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('fecha_baja', models.DateField()),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_sindical.sindicato')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_sindical.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='AsambleaAfiliados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_trabajadores', models.IntegerField()),
                ('cantidad_acuerdos', models.IntegerField()),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_sindical.sindicato')),
            ],
        ),
    ]
